### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by DaFri-Nochiterov** [qeled/discordie#11]
"Sometimes" when you call methods they returning a 502 error. Discord API documentation says `Wait a bit and retry`. I think you should make an some loop for calls, because if you will do that in your bot code this code will look like a.. shitcode

```js
var tries = 0;
var loop = () => {
  channel.sendMessage("Hello world!").then(cb, (err) => { 
     if(err) {
       // TODO: Error checking
       // For example now this error is 502
     }
    if(tries++ > 5) { return cb(err); }
    loop();
  });
}
loop();
```

instead of

```js
channel.sendMessage("Hello world!").then(cb).catch(cb);
```

**Comment by CKing** [comment]
Create your own promise callback for that. 
There are other similar errors as well. 
I'm using a custom promise callback for that. 

```
channel.sendMessage("Hello world!").then(waitAndRetry).then(cb).catch(cb);
```

**Comment by qeled** [comment]
Added https://github.com/qeled/discordie/commit/2efebe6ef2d3ca411bc547957ad6550ae035c1b3

**Comment by DaFri-Nochiterov** [comment]
Thanks you!
