### ISSUE TITLE
Send message to specific channel

### ISSUE THREAD

**Issue by ghost** [qeled/discordie#114]
I can't figure out how to send a message to a channel of my choice - I want the bot to send a message to #general-chat when it starts up but I can't find anything anywhere about to do that

**Comment by Edsardio** [comment]
Look here:
http://qeled.github.io/discordie/#/docs/Discordie?p=Discordie%23Channels&_k=v0s3ou
Then look here:
http://qeled.github.io/discordie/#/docs/IChannelCollection?_k=pp5kze
Then look here:
http://qeled.github.io/discordie/#/docs/ITextChannel?p=ITextChannel%23sendMessage&_k=nc4hqd

Good luck

**Comment by ghost** [comment]
Thanks but I've already read through all of that and none of it has helped

**Comment by Edsardio** [comment]
var channel = client.Channels.get('ID');
channel.sendMessage('Message');

**Comment by ghost** [comment]
Thank you so much - I was trying to do client.guild.Channels.get("ID")

Case closed, tyvm ❤️
