### ISSUE TITLE
How to test for roles of author of sent message

### ISSUE THREAD

**Issue by ghost** [qeled/discordie#115]
After a message is sent, I'd like to test for whether or not the author of the message has a specified role. How would I do this? The documentation is complicated and confusing to read.

**Comment by linuswillner** [comment]
There is a method on the IGuildMember object called .hasRole(), so you’re not looking in the right place.

Besides, deeming from your last issue, it sounds like your inability to understand the documentation comes down to you not knowing the language.

**Comment by ghost** [comment]
Yeah that's correct - I've been programming for 7 years but I've done very little javascript

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/19936923/34068839-aae946c6-e1f7-11e7-8d52-83b975411da5.jpg)
What do I do now

**Comment by linuswillner** [comment]
As the docs say, IMessage.author is an IUser instance, not IGuildMember. You need to access the `member` property on an IMessage object.

**Comment by Edsardio** [comment]
I suggest you join the Discord server https://discord.gg/discord-api
