### ISSUE TITLE
How does the rest.auth work?

### ISSUE THREAD

**Issue by JacobTDC** [qeled/discordie#118]
I tried to use this library as a way to figure out how to login, but when I use 
```js
var xhttp = new XMLHttpRequest();
xhttp.onreadystatechange = function() {
  if (this.readyState == 4) {
    alert(this.responseText);
  }
};
xhttp.open("POST", "https://discordapp.com/api/auth/login", true);
xhttp.setRequestHeader("Content-Type", "application/json");
xhttp.send(JSON.stringify(auth));
```
it returns `{"captcha_key": ["captcha-required"]}`.
What captcha? There is nothing in the Discordie code about this captcha. How does it login?

**Comment by Edsardio** [comment]
This has nothing to do with the library. I suggest you look into passport

**Comment by JacobTDC** [comment]
Okay. Most certainly will. Sorry about posting here, @Edsardio, I just had nowhere else to find the needed information, no matter where I looked. This library is the only code I could find that successfully logs in to Discord using an email and password.

**Comment by ghost** [comment]
@JacobTDC Using non-documentated endpoints (such as `/auth/login`) is strictly forbidden. Userbots are aswell forbidden and results in a platform ban. If you want to make a "Login with Discord" thing, use OAuth 2.0.

**Comment by JacobTDC** [comment]
I'm a developer, and I need *full* account access. To test a protocol.

**Comment by ghost** [comment]
"I'm a developer" is no excuse for anything. If you need access to the account, use RPC (which requires your app to get whitelisted). Otherwise you risk your account.

**Comment by JacobTDC** [comment]
It's also *only* bannnable if you use 2-Factor-Auth,  @CharlotteDunois.

**Comment by JacobTDC** [comment]
I meant to put that in the previous message, but I accidentally sent it, and you can't edit on mobile.

**Comment by JacobTDC** [comment]
At least, that's what I read, @CharlotteDunois. Please correct me if I'm wrong.

**Comment by ghost** [comment]
![grafik](https://user-images.githubusercontent.com/4529744/34212469-a6e6bca4-e59c-11e7-96c3-b4be56b31301.png)
Both are bannable.

**Comment by JacobTDC** [comment]
Oh, I don't plan on automating it, I am just doing it for the sake of learning.

**Comment by JacobTDC** [comment]
Well, that was stated wrong. I meant, I'm trying to make a webpage that allows sending of embeds from users.

**Comment by JacobTDC** [comment]
Sorry for any confusion, I'm just having trouble forming sentences from thoughts right now.

**Comment by ghost** [comment]
Use a webhook.

**Comment by JacobTDC** [comment]
That's... Actually a good solution... Thanks @CharlotteDunois... I hadn't thought of that...
