### ISSUE TITLE
client.User.setGame() not doing anything.

### ISSUE THREAD

**Issue by ajgeiss0702** [qeled/discordie#120]
I am making a simple bot just to play around with some of the features. I try to set the game, but nothing happens. Here is my code for it:
```
client.Dispatcher.on(Events.GATEWAY_READY, e => {
  console.log("Connected as: " + client.User.username);
  var game = {
    name: 'the best game'
  };
  client.User.setGame(game);
});
```
I have also tried simply giving it a string, same result.

Am I doing something wrong?

**Comment by Edsardio** [comment]
Should switch to the dev branch for this to work, Q isn't really active so he hasn't pushed it to master yet

**Comment by ajgeiss0702** [comment]
Ok, thanks

**Comment by ajgeiss0702** [comment]
How can I switch to the dev branch from node?

**Comment by linuswillner** [comment]
`npm install github:qeled/discordie#dev`

**Comment by ajgeiss0702** [comment]
Thank you.
