### ISSUE TITLE
.setGame() and .setStatus() documentation is incorrect.

### ISSUE THREAD

**Issue by ghost** [qeled/discordie#126]
`client.User.setGame("with code");` doesn't set the bot's status to "Playing with code"
neither does `client.User.setGame({name: "with code"});`

The only thing i've found that works is `client.Users.setGame({type: 0, name: "with code"});`

This should be updated in documentation.

**Comment by curtisf** [comment]
This is fixed in the dev branch.

**Comment by ghost** [comment]
@caf203 why isn't it in master?

**Comment by curtisf** [comment]
If you haven't noticed, this repository is basically dead.

**Comment by ghost** [comment]
@caf203 why doesn't he just merge it with master?

**Comment by rjm-codes** [comment]
probably still in development and unstable
