### ISSUE TITLE
No Voice in IPermissions

### ISSUE THREAD

**Issue by DaFri-Nochiterov** [qeled/discordie#14]
`IPermissionOverwrite` for voice channel has no `Voice` in `deny` and `allow` (which both are `IPermissions`)

![image](https://cloud.githubusercontent.com/assets/10401817/16476248/b34236ee-3eaf-11e6-8c66-6c1939250f30.png)

**Comment by qeled** [comment]
Pretty sure I fixed that 12 days ago in https://github.com/qeled/discordie/commit/30af2df026780f8b98765a07c939407b24a83a35 - should be working on 0.7.0 and above.

**Comment by DaFri-Nochiterov** [comment]
I thought my packages was updated, because I run `npm update` and [it should update all dependencies listened at `package.json`](https://docs.npmjs.com/getting-started/updating-local-packages), before I start bot. Agrh, npm..

Tested, this really works.

Sorry for disturb =(
