### ISSUE TITLE
Position number in .roles has no number.

### ISSUE THREAD

**Issue by Ryu945** [qeled/discordie#17]
Two weeks ago, when I called .roles on IGuildMember object; the variable position would give you a number based on rank.  Now every ranks' number is 1.  This needs to be fixed.

**Comment by qeled** [comment]
Simple reordering in the client will probably fix that. Please check the actual position value sent by the server, since the library just transparently stores them.

Here's a role position dump from my end, everything seems to be fine:
```js
> guild.roles.sort((a,b) => a.position - b.position).map(g => g.position)
[ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ]
```

**Comment by Ryu945** [comment]
Reordering fixed it.  What is to keep this from breaking again?

**Comment by qeled** [comment]
Some libraries might not implement reordering consistently, so if there are other bots changing role positions - they could be the source of this.

**Comment by Ryu945** [comment]
There are no other bots changing roles.  It just happened.

**Comment by abalabahaha** [comment]
Sometimes role or channel positions can end up occupying the same position number when dragged around in Discord client. I think it's being worked on.
