### ISSUE TITLE
ratelimit issue

### ISSUE THREAD

**Issue by tonkku107** [qeled/discordie#19]
I send my help command in DMs, it's a long message and after it's sent, the bot slows down with all future messages with incrementally higher delays (at first it's 15 seconds but then it's like 5 minutes)
Sending many small messages is fine tho for some weird reason.

It shouldn't slow down on large messages, it should slow down for a short time (not forever), when alot of messages are being sent individually.

**Comment by qeled** [comment]
Message length shouldn't matter. Currently all messages are put into a single queue, so there is a possibility that your bot was being spammed or just sending a lot of messages at that time. This issue is known and being worked on.

**Comment by tonkku107** [comment]
I realized I am sending another message after 0.5 seconds in the help, setting it to 1 second worked around the issue.

It wasn't alot, and sending many messages with like 2 or 3 seconds in between is still fine

**Comment by dustinblackman** [comment]
We've been experiencing the same thing with Gravebot during peak hours but weren't sure if the blame was on Discordie or something else. Is there an option to disabling rate limiting management for time being?

**Comment by qeled** [comment]
There's an undocumented constructor option for disabling rate limit handling - that will pass 429 errors to the promise catch handler and might cause messages to be sent out of order:
```js
var client = new Discordie({messageQueue: false});
```

**Comment by qeled** [comment]
If it's that serious I guess I'll abandon for a while my attempt at preemptive ratelimit handling implementation with nested bucket support that I've been planning and try to code just a simple tree of queues, ETA - tomorrow.

**Comment by tonkku107** [comment]
Thanks

**Comment by qeled** [comment]
Ready for testing in the dev branch https://github.com/qeled/discordie/commit/6b29ae719daed81de4bebb8bd782432f3e13c0dc

**Comment by qeled** [comment]
Fixed in version 0.7.5.
