### ISSUE TITLE
Crashes without manage message permission

### ISSUE THREAD

**Issue by Ryu945** [qeled/discordie#21]
if you delete a message when the bot does not have the privilege to delete a message, it crashes the program.  An example of this is ``e.message.delete();``

**Comment by qeled** [comment]
Unable to reproduce.
```js
> c.messages.find(g => !g.deleted).delete().catch(err => console.log(err.message))
Promise { <pending> }
Forbidden (Missing Permissions)
```

**Comment by Ryu945** [comment]
I tested it again.  It no long has this problem.  I think you did an update that fixed it when you were working on another problem.  I noticed this problem back when the nodejs updated caused the program to crash.

**Comment by qeled** [comment]
Then it wasn't caused by `message.delete()` then. Would be nice if you included stack traces in all of your future reports, if any.
