### ISSUE TITLE
EncodeWorker being a performance hog

### ISSUE THREAD

**Issue by neico** [qeled/discordie#23]
First I was wondering why my bot was using so much cpu time, when I found `multiThreadedVoice` in the code and tried it out it became apparent. EncodeWorker is using way too much cpu time for a single voice connection, let's get some stats:

My server has a Intel 8x 2,13Ghz CPU, which is pretty average, but works quite well for everything I've done so far.
Now enter EncodeWorker, this thing is taking 10% of the entire cpu, per VoiceConnection.
I then found the Profiler code inside and decided to give it a spin:
```
...
[MIX] 28.34ms 0.38%cpu; [RES] 29.21ms 0.40%cpu; [ENC] 936.75ms 12.68%cpu; [TOTAL] 994.30ms 13.46%cpu; T: 7385.03
[MIX] 33.00ms 0.38%cpu; [RES] 33.09ms 0.38%cpu; [ENC] 1022.10ms 11.82%cpu; [TOTAL] 1088.18ms 12.59%cpu; T: 8644.59
[MIX] 28.52ms 0.38%cpu; [RES] 29.37ms 0.39%cpu; [ENC] 940.71ms 12.64%cpu; [TOTAL] 998.60ms 13.41%cpu; T: 7444.84
[MIX] 33.19ms 0.38%cpu; [RES] 33.25ms 0.38%cpu; [ENC] 1026.40ms 11.79%cpu; [TOTAL] 1092.84ms 12.55%cpu; T: 8705.87
[MIX] 28.74ms 0.38%cpu; [RES] 29.58ms 0.39%cpu; [ENC] 945.85ms 12.60%cpu; [TOTAL] 1004.17ms 13.38%cpu; T: 7506.48
[MIX] 33.38ms 0.38%cpu; [RES] 33.41ms 0.38%cpu; [ENC] 1030.46ms 11.76%cpu; [TOTAL] 1097.25ms 12.52%cpu; T: 8764.78
[MIX] 28.92ms 0.38%cpu; [RES] 29.73ms 0.39%cpu; [ENC] 949.83ms 12.55%cpu; [TOTAL] 1008.49ms 13.33%cpu; T: 7565.59
[MIX] 33.57ms 0.38%cpu; [RES] 33.57ms 0.38%cpu; [ENC] 1034.51ms 11.72%cpu; [TOTAL] 1101.65ms 12.48%cpu; T: 8824.70
[MIX] 29.11ms 0.38%cpu; [RES] 29.89ms 0.39%cpu; [ENC] 954.28ms 12.51%cpu; [TOTAL] 1013.28ms 13.29%cpu; T: 7625.51
[MIX] 33.75ms 0.38%cpu; [RES] 33.73ms 0.38%cpu; [ENC] 1038.51ms 11.69%cpu; [TOTAL] 1105.99ms 12.45%cpu; T: 8885.13
```
So encoding seems to take quite some time, I then decided to try out "node-opus" which actually dropped the cpu usage down to 5-7% which is still pretty much considering that I have a madplay and lame process running on the same machine which only takes 3-5%.

For reference, here's what the profiler says with "node-opus":
```
...
[MIX] 14.92ms 0.44%cpu; [RES] 0.56ms 0.02%cpu; [ENC] 92.04ms 2.74%cpu; [TOTAL] 107.53ms 3.20%cpu; T: 3362.71
[MIX] 24.85ms 0.57%cpu; [RES] 0.50ms 0.01%cpu; [ENC] 126.08ms 2.92%cpu; [TOTAL] 151.43ms 3.50%cpu; T: 4322.01
[MIX] 15.25ms 0.45%cpu; [RES] 0.57ms 0.02%cpu; [ENC] 94.44ms 2.76%cpu; [TOTAL] 110.26ms 3.22%cpu; T: 3423.28
[MIX] 25.19ms 0.57%cpu; [RES] 0.51ms 0.01%cpu; [ENC] 128.58ms 2.93%cpu; [TOTAL] 154.28ms 3.52%cpu; T: 4383.94
[MIX] 15.57ms 0.45%cpu; [RES] 0.57ms 0.02%cpu; [ENC] 96.81ms 2.78%cpu; [TOTAL] 112.95ms 3.24%cpu; T: 3483.41
[MIX] 25.46ms 0.57%cpu; [RES] 0.51ms 0.01%cpu; [ENC] 130.51ms 2.94%cpu; [TOTAL] 156.48ms 3.52%cpu; T: 4442.83
[MIX] 15.90ms 0.45%cpu; [RES] 0.57ms 0.02%cpu; [ENC] 99.13ms 2.80%cpu; [TOTAL] 115.61ms 3.26%cpu; T: 3543.08
[MIX] 25.66ms 0.57%cpu; [RES] 0.51ms 0.01%cpu; [ENC] 131.97ms 2.93%cpu; [TOTAL] 158.14ms 3.51%cpu; T: 4503.11
[MIX] 16.23ms 0.45%cpu; [RES] 0.58ms 0.02%cpu; [ENC] 101.54ms 2.82%cpu; [TOTAL] 118.36ms 3.28%cpu; T: 3603.45
[MIX] 25.86ms 0.57%cpu; [RES] 0.52ms 0.01%cpu; [ENC] 133.35ms 2.92%cpu; [TOTAL] 159.73ms 3.50%cpu; T: 4561.74
```

That's all well and such, but with "node-opus" I seem to have audio stutters all over the place (at least they're more noticeable and more frequently), so this can't be a solution in the long term as well...

So the basic encoding seems slow by default, while the Worker itself seems to have more places that slow it down quite a bunch, I don't really know if there are other tweaks beside "node-opus" and `multiThreadedVoice` to make the performance better.
I only have my bot on 2 guilds (servers) so far and it's already taking 20% (with "node-opus" a bit less), I can't imagine how this will end when more pickup the bot...

Feel free to take a look at my code if you have reason to think that it's actually a side-effect of my own code: https://github.com/yas-online/osustation-discord/blob/master/lib/client.js#L385

PS: speaking of the Worker, it would be great if you could pass things like `execArgv` to the `fork()` call, for things like changing the debugger port per process, or simply ignoring the debugger args on it...

**Comment by qeled** [comment]
Option `multiThreadedVoice` has never been documented and should not be used at all, in the first case it is the performance hog because of bad IPC.
For reference, on my machine (AMD FX8120) emscripten opus is about 1.8x slower than `node-opus` with `multiThreadedVoice` disabled.

Also for now I suggest using [FFmpegEncoder](https://qeled.github.io/discordie/#/docs/FFmpegEncoder) for transcoding (and passing stream url to it), so that some part of networking IO and transcoding to opus is done in a separate process. And audio stutters you've been hearing is probably packet loss.

If you want to optimize it even further, you probably should use a transcoding server that can encode a single stream of opus, then you can avoid FFmpeg and stream without transcoding in node/FFmpeg by using `Webm/OggOpusPlayer`.

Some tests from my machine:
- Single transcoding stream (lame + EncoderWorker + node-opus) is about 16% of cpu core.
- FFmpegEncoder (mp3 file to opus): about 4-7%.
- Streaming an opus file with `OggOpusPlayer`/`WebmOpusPlayer` takes about 3.5%.

I guess with these optimizations your CPU could probably handle 250-400 streams.

**Comment by qeled** [comment]
I experimented with your idea a bit and here's somewhat working concept that encodes the stream only once: https://gist.github.com/qeled/885e390cb0eb3661cf43e850617c82ed (pardon the ugliness). Feel free to use it if you want. Don't think this should be a part of the library though.

**Comment by neico** [comment]
Guess I'll experiment with that information a bit then, thanks anyway.

**Comment by neico** [comment]
So, it took quite a while but after modifing [node-lame](https://github.com/yas-online/node-lame) & [node-opus](https://github.com/yas-online/node-opus) I was finally able to strip the bot down to 1 stream, 1 decoder and 1 encoder. (though both packages still need some work, opus for example doesn't use SSE instructions on linux yet)

This resulted in a cpu usage drop from around 40% (with around 7 discord server connections) to 4-10%

I might post some solid statistics at some point here but for now I'll see how things run in long term.
But I'll close this for now as the initial huge impact is now gone. (and probably shouldn't reappear)
