### ISSUE TITLE
Get Channel By ID

### ISSUE THREAD

**Issue by Lolums** [qeled/discordie#24]
`bot.Channels.get(channel_id);` returns null.

The channel definitely exists :)

**Comment by qeled** [comment]
Let me guess: it is a direct message channel and is located in the `DirectMessageChannels` collection, not `Channels`?

**Comment by Lolums** [comment]
Nah, I was selecting the ID from MySQL and it kept getting rounded down due to floating point precision - not your fault :p

27.07.2016, 12:30, "qeled" <notifications@github.com>:
