### ISSUE TITLE
Changed reply function?

### ISSUE THREAD

**Issue by troffaholic** [qeled/discordie#39]
Is there a new update where you changed the `reply` function?
I use `e.message.reply(...)` but I doesn't send anything. The exact same code worked 15-20 hours ago.
Also, I don't get any error message or crash and the code is being ran: I have a `console.log(...)` in the same block.

Sorry if I'm being too specific.

**Comment by troffaholic** [comment]
Apparently my token was automatically changed for some reason.

**Comment by troffaholic** [comment]
But updating token information didn't fix it...

**Comment by qeled** [comment]
Discord started to force prefixed bot tokens recently. You're probably running it on an old version of the library, automatic bot token detection was introduced 3 weeks ago in version 0.8.0.

If updating is not an option right now, in older versions (0.4.0+) you should be able to specify it manually with:
```js
var client = new Discordie();
client.bot = true;
```

**Comment by troffaholic** [comment]
I started making the bot yesterday.

**Comment by troffaholic** [comment]
Thank you.

Using `client.bot = true` actually fixed it.
Although I think it's very strange, since it worked all fine yesterday.
