### ISSUE TITLE
Name of role

### ISSUE THREAD

**Issue by DaFri-Nochiterov** [qeled/discordie#4]
Can I view name of `IRole`?

For example `@everyone` or `Admin`

**Comment by abalabahaha** [comment]
does `role.name` work?

**Comment by qeled** [comment]
The documentation was missing those indeed, but `role.name` and other properties listed in (now fixed) [IRole docs](https://qeled.github.io/discordie/#/docs/IRole) should work, thanks for the report.

**Comment by DaFri-Nochiterov** [comment]
Thanks you for quick reply :)
