### ISSUE TITLE
Any way to play music?

### ISSUE THREAD

**Issue by troffaholic** [qeled/discordie#42]
Hello,

A much requested feature for bots is music-playing.
Is there support for that in Discordie? 
Now I know that there are bots that can play music but they don't necessarily have to use Discordie

Anyways, is there support for it and if so, how do I use it?

**Comment by acdenisSK** [comment]
1. Yes it is supported.
2. There are examples for music already. Most notably https://github.com/qeled/discordie/blob/master/examples/ffmpegencoder.js and https://github.com/qeled/discordie/blob/master/examples/encoderstream.js

**Comment by troffaholic** [comment]
Thank you.
