### ISSUE TITLE
Support sendMessage (and similar methods) accepting Arrays joined by newline

### ISSUE THREAD

**Issue by ghost** [qeled/discordie#47]
I know it's a fairly simple thing...but I've become accustom to sending Arrays of messages, and it would be handy if the lib would accept them as an Array.  Helps clean up the codes a bit.  =)

**Comment by briantanner** [comment]
This is a very small detail, but I have to say that I became accustomed to this as well, and I'm still catching the odd error where I forgot to `.join('\n')` lol
