### ISSUE TITLE
High CPU usage from voice and typing events

### ISSUE THREAD

**Issue by dustinblackman** [qeled/discordie#5]
With bots that have a large user base (+4000 servers, +90000 users), voice events and typing events cause CPU usage to go quite high. On a i7 2015 Macbook pro, it has CPU average of 30-40%. On a small digital ocean instance, or a free heroku tier, that's a constant 100% CPU before an eventual crash.

By manually disabling voice events and typing events found through CPU profiling, CPU average drops to 3-4% average. A dirty fix looks like [this](https://github.com/Gravebot/discordie/commit/515c6d9aaccbc7f67cc2418a7982b80131e974fb).

Best bet would be adding an option to disable listening for these events, if a bot doesn't require them. I'll try to put up a PR for it this week if I can find the time, but could be quick fix for you. Thanks.

**Comment by hlaaftana** [comment]
Sorry for being abrupt, but what is your bot's name even? 4000 servers is a LOT, it'd be the bot with the third most servers in this list.

**Comment by dustinblackman** [comment]
Gravebot.

**Comment by qeled** [comment]
Thanks, I'm aware of the slightly bad VOICE_STATE_UPDATE handling performance since TXJ was running into it, but typing events is something new - noted, will look into it later (won't be home tomorrow so maybe tuesday) and try to optimize and maybe add an option to disable these events as you suggested.

**Comment by dustinblackman** [comment]
That'd be awesome! Thanks a lot.

**Comment by qeled** [comment]
@dustinblackman
Pushed state tracking optimizations, test results so far on a mockup (`READY` dump from a bot account) with 2k guilds:

```
1000 iterations (2 calls per iteration - join and leave)
                                   time  disabled  opt
>> before optimization          24788ms      233x  37x
>> opt with changes listener     1810ms       17x   3x
>> opt without changes listener   670ms        6x   1x
>> no voice state tracking        106ms        1x    
```

If you don't have any listeners for `VOICE_CHANNEL_*` and `VOICE_USER_*` events the `opt without changes listener` entry will apply.

Events `TYPING_START` and `PRESENCE_UPDATE` now also won't fire too if you have no listeners for them.

That probably eliminates the need for an option to disable state tracking, but we'll see.

Try updating to dev branch when you can (would also like to know how much CPU usage differs with the optimizations and your changes that disable state tracking completely), thanks again!

**Comment by dustinblackman** [comment]
Much much better! CPU is averaging the same as with my fork. Well done, thanks!

I ran another CPU profile, while the usage is somewhat low, there's two other events that look voice related firing.

<img width="1180" alt="screen shot 2016-04-18 at 7 49 10 pm" src="https://cloud.githubusercontent.com/assets/5246169/14623558/51d9e97a-05a1-11e6-8e16-ecdea96043b7.png">

**Comment by qeled** [comment]
That's not exactly critical since it's only 3% of all CPU time (and it processes voice states so methods like `IUser.getVoiceChannel` still return correct values, not firing events), but still - I pushed second optimization pass, it's about 3-4x faster (probably more on a real setup) compared to previous.

**Comment by dustinblackman** [comment]
All looks great. I'll leave this open until you're ready to close it with your next release. Thanks again for the help!

**Comment by qeled** [comment]
Closing as it's already in version 0.5.5.

**Comment by dustinblackman** [comment]
👍
