### ISSUE TITLE
User cache doesn't clear

### ISSUE THREAD

**Issue by Meowbeast** [qeled/discordie#50]
![image](https://cloud.githubusercontent.com/assets/22228023/18615547/07fc96fe-7d6f-11e6-9b30-a56274eeea1a.png)

I recently had my bot leave all servers...and the user count did drop, but stayed pretty high.

I thought it might need some time to gc or clear...so I left it overnight.  It seems the user cache didn't clear.  I've added my bot back to 2 servers, but the user count should be < 50.

**Comment by Ryu945** [comment]
Direct messages add to the user count.  Have your bot close all open direct messages and you should see the user count drop.

**Comment by ttftw** [comment]
Closing because I guess no one reads or responds to issues... lol.
