### ISSUE TITLE
Guild roles show as empty

### ISSUE THREAD

**Issue by arunesh90** [qeled/discordie#51]
![image](https://cloud.githubusercontent.com/assets/5787588/19015882/36a06fb4-880d-11e6-9cd6-b7708e2765c4.png)

the roles object is supposed to be a array with different roles.
Instead its a empty object

**Comment by TheEvilSocks** [comment]
![Image](https://u.pomf.is/vvqbmy.png)

**Comment by troffaholic** [comment]
Do you have any roles except `@everyone`?
