### ISSUE TITLE
voiceConnection.disconnect() "stops" playback on other guilds

### ISSUE THREAD

**Issue by TheBITLINK** [qeled/discordie#53]
If a bot is playing music on multiple guilds, and i do voiceConnection.disconnect() in one of these, the audio stops on the other guilds.

However, if users re-join the voice channels in the other guilds, they are able to hear the bot again.

I'm on the dev branch, i tested with my own bot and also the ffmpegEncoder example present on the repo, just to make sure.

**Comment by qeled** [comment]
I can only reproduce this if the listening client is a member of both guilds, and since Wireshark still shows audio packets going both ways - seems like an issue with the Discord client, not the library. Being able to reconnect as a client and hear it again only confirms it.
