### ISSUE TITLE
Broken emoji sometimes

### ISSUE THREAD

**Issue by DaFri-Nochiterov** [qeled/discordie#54]
Two of my bots use discordie library. And I noticed, that sometimes after sending, emoji completely broken in message.

One bot adds `:DiscordIcon:` emote to twitch chat messages:
![image](https://cloud.githubusercontent.com/assets/10401817/20099398/db0070cc-a5ea-11e6-97ab-779403d8fc09.png)

Second bot failed at eval\*:
![image](https://cloud.githubusercontent.com/assets/10401817/20099483/403bc2b6-a5eb-11e6-9d3a-93e972e71af1.png)

````javascript
.r_eval ``let emoteList = $.Guild.emojis.map(em => "<:"+em.name+":"+em.id+"> - "+em.name);
let emToSend = [];
emoteList.forEach((emote,index)=> {
   emToSend.push(emote);
   if(emToSend.length === 10 || index === (emoteList.length - 1)) {
       $.Reply(emToSend.join("\n"));
       emToSend = [];
   }
});
``
````

by adding some code we can check, that emoji really broken:
![image](https://cloud.githubusercontent.com/assets/10401817/20099773/e9ee18d0-a5ec-11e6-92c3-303d1410df79.png)

\* - any emotes starting with `dwillis` can be used only by subscribers, so bot can't use them, it's OK

**UPD**: Some guy on Discord.API server told me, that emotes also [have ratelimit](https://i.imgur.com/KBNcZ.gif):

![image](https://cloud.githubusercontent.com/assets/10401817/20099906/7815ed4a-a5ed-11e6-8035-b341216fe37d.png)

So may be add some handler for this? 🤕 

Thanks!

**Comment by MinnDevelopment** [comment]
That was meant for reactions not emotes.

**Comment by MinnDevelopment** [comment]
If you use an emoji formatted like `<:name:id>` with a valid id that you are unable to use all emojis using that format will automatically be converted to `:name:` and display as such.
So make sure you have access to all the emojis you use in the messages.

=====
### Consider: 
- The roles it is restricted to
- Your permissions in the current channel
- Do you know the source of the emoji
- Is the emoji managed or not

**Comment by DaFri-Nochiterov** [comment]
Oh, sorry. We didn't understand each other.

These emotes available to bot:
![image](https://cloud.githubusercontent.com/assets/10401817/20114796/43b03e8a-a628-11e6-8464-8d521f449268.png)

But final result:
![image](https://cloud.githubusercontent.com/assets/10401817/20114800/513b3ec4-a628-11e6-9c32-a2a218343dd7.png)

When next message (which was sent after ~4 seconds from this broken message) is absolutely fine

**Comment by MinnDevelopment** [comment]
I broke it down in my comment before, if the bot is unable to use one of the emojis in the message all emojis in that message will be converted to `:name:` and not display as emoji.

**Comment by DaFri-Nochiterov** [comment]
Not cool. So it's Discord's thing?
![image](https://cloud.githubusercontent.com/assets/10401817/20116090/754340b4-a62d-11e6-8782-ea77d8f486f0.png)

**Comment by MinnDevelopment** [comment]
Yes, "it's Discord's thing"

**Comment by DaFri-Nochiterov** [comment]
So sad. But OK. Thanks you.
