### ISSUE TITLE
How to apply .toLowerCase(); / .toUpperCase();

### ISSUE THREAD

**Issue by Lukkez** [qeled/discordie#55]
How to apply .toLowerCase(); / .toUpperCase(); on a message, someone can send a example? I dont speak to many english, sory if it is bad

**Comment by GusCaplan** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toLowerCase
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toUpperCase

**Comment by Lukkez** [comment]
" I dont speak to many english, sory if it is bad" how i'm read if i dont know english, can send a example?

**Comment by briantanner** [comment]
Read it in another language.

**Comment by aurieh** [comment]
Someone needs to close this, not related to discordie in any way.

**Comment by Edsardio** [comment]
var str = e.message.content;
e.message.content.toLowerCase();

**Comment by Lukkez** [comment]
i know is this closed but someome can send the fullyy code
