### ISSUE TITLE
bot goes to sleep unwanted

### ISSUE THREAD

**Issue by s-a** [qeled/discordie#57]
Hey, I wrote a bot hosted on Heroku and my problem is that the bot goes offline . I guess after 12 or 20 hours or something like that. I keep the heroku app alive with a webserive call ervery five minutes. When I check the heroku app I can confirm that the heroku app is not sleeping. Is this a comon problem? How to wake up the bot ?

**Comment by GusCaplan** [comment]
this isn't a discordie problem, you would be more suited to ask on the heroku forums about ways to keep your container running.

**Comment by TTtie** [comment]
Agreeing with Gus, this isn't an issue on discordie side and doesn't have anything to do with it(unless you're dumb and didn't turn on auto reconnecting)

**Comment by s-a** [comment]
Thank you for fast reply. I missed the ```autoReconnect``` feature.

**Comment by Ryu945** [comment]
Auto reconnect is still their.  Your hoster is putting you bot to sleep so it can't connect.
