### ISSUE TITLE
Missed methods in docs

### ISSUE THREAD

**Issue by DaFri-Nochiterov** [qeled/discordie#6]
From example on "Getting started" page:

```javascript
client.Dispatcher.on("MESSAGE_CREATE", e => {
  if (e.message.content == "ping")
    e.message.channel.sendMessage("pong");
});
```

Here we see method `sendMessage` of `channel`.

In documentation of ["IMessage"](https://qeled.github.io/discordie/#/docs/IMessage) object: 
> * .channel => [**IChannel**](https://qeled.github.io/discordie/#/docs/IChannel) | [**IDirectMessageChannel**](https://qeled.github.io/discordie/#/docs/IDirectMessageChannel) | **null**

In documentation of ["IChannel"](https://qeled.github.io/discordie/#/docs/IChannel) object we don't see method "sendMessage", which given in example.

Only these:

> * .createInvite(options) => **[Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise)\<[Object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object), [Error](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error)\>**
> * .createPermissionOverwrite(roleOrMember, [allow], [deny]) => **[Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise)\<[IPermissionOverwrite](https://qeled.github.io/discordie/#/docs/IPermissionOverwrite), [Error](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error)\>**
> * .update([name], [topic], [bitrate]) => **[Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise)\<[IChannel](https://qeled.github.io/discordie/#/docs/IChannel), [Error](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error)\>**
> * .setPosition(position) => [**Promise**](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise)
> * .delete() => [**Promise**](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise)
> * .getInvites() => **[Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise)\<[Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array)\<[Object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object)\>, [Error](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error)\>**

**Comment by qeled** [comment]
Thanks again, it's supposed to be referencing `ITextChannel` instead of `IChannel`, fixed that and couple of other references, also added a description to [`IChannel`](https://qeled.github.io/discordie/#/docs/IChannel) stating that it's just a base class.
