### ISSUE TITLE
how do i use iguild

### ISSUE THREAD

**Issue by kessanro** [qeled/discordie#61]
i dont know how to use iguild it does not work properly
specificity

- [ ] 1. iguild.name
- [ ] 2. iguild itselth

anyway of adding it like a require

**Comment by joejoesam1** [comment]
**Number One: ** Don't post help request in issues, it's not a bloody issue.
**Number Two: **  Read the Docs™.
**Number Three: ** Learn JS. And I mean that.
**Number Four: ** Common Sense™
**Number Five: ** Learn spelling, it's itself not itselth.

**Comment by joejoesam1** [comment]
**e**

**Comment by TTtie** [comment]
To be honest, the lib provides and might emit an object or in IMessage and IGuildMember interface with `guild`, which is actually `IGuild`. Read the documentation next time, kthx

**Comment by programmer135** [comment]
@joejoesam1 shut the fuck up

**Comment by joejoesam1** [comment]
@programmer135 idk who the heck you are and i've never banned anyone from a discord server so shut up ur mouth

**Comment by joejoesam1** [comment]
@programmer135 what server was it on and who was it?
