### ISSUE TITLE
PRESENCE_UPDATE fires multiple times

### ISSUE THREAD

**Issue by Edsardio** [qeled/discordie#67]
On updating status from online to invisible the event gets fired once, updating from online to do not disturb fires 3 times. (That's what I logged as last)
Changing the game fires twice or more as well. How to fix this?

**Comment by qeled** [comment]
Presences are per-guild - it fires a presence for each shared guild with your bot. This is how the API works.

You can compare `previousStatus`, `previousGameName`, and/or simply throw away presences for guilds you don't want to process.
