### ISSUE TITLE
Get user email from IUser

### ISSUE THREAD

**Issue by TheDoctorsLife** [qeled/discordie#68]
Discord's API looks like it should return a user's email from ``/users/{id}`` through the user object it returns, but this method doesn't exist in discordie, so I'm opening this issue to get that in.

**Comment by abalabahaha** [comment]
It only returns an email if you're requesting `/users/@me` or making an OAuth-based request with identify+email scopes

**Comment by qeled** [comment]
Endpoint `/users/:id` has never returned emails and likely never will. You need to explicitly request OAuth permissions from the user to fetch it through `/users/@me` with an OAuth token as said above.

This is beyond the scope of this library.
