### ISSUE TITLE
Check if user has Nitro?

### ISSUE THREAD

**Issue by DaFri-Nochiterov** [qeled/discordie#69]
Can you add property `premium` to `IUser` and `IGuildMember`?

Discord already returns these properties: 
![image](https://cloud.githubusercontent.com/assets/10401817/22241017/269c147c-e250-11e6-9f7a-e569d8473c40.png)

**Comment by aurieh** [comment]
iirc it only sends those if the authenticated account is a userbot.

**Comment by DaFri-Nochiterov** [comment]
Yep, you're right about userbot. But this still can be added with warning about unavailability for bots.

**Comment by aurieh** [comment]
Then again, I see a free pull request 👀

**Comment by qeled** [comment]
It was implemented but never pushed to any of the public branches because:
1. Some people might want to spam this endpoint and could get banned;
2. Ratelimits for user-only endpoints are not exposed (and even if known, should not be hardcoded);
