### ISSUE TITLE
@here mention (Request)

### ISSUE THREAD

**Issue by drdrjojo** [qeled/discordie#7]
Message.mention_everyone should be set to true like by @everyone

**Comment by qeled** [comment]
That does seem to be working just fine?

```
> client.Messages.map(g => "[" + g.timestamp + "] " + g.content + " -> " + g.mention_everyone);
[ '[2016-04-25T13:25:13.213000+00:00] @everyone -> true',
  '[2016-04-25T13:25:21.166000+00:00] @here -> true',
  '[2016-04-25T13:25:36.031000+00:00] just a message -> false' ]
```

Also this property is only a transparent wrapper, the library doesn't modify it at all. If it persists report this issue to the Discord developers on [the API server](https://discord.gg/0SBTUU1wZTWPnGdJ) instead as I am not in charge of the API.
