### ISSUE TITLE
guild.members.length returns invalid value

### ISSUE THREAD

**Issue by brawaru** [qeled/discordie#81]
```js
guild.members.length
```

returns invalid value:

![image](https://cloud.githubusercontent.com/assets/10401817/23179171/8c66710c-f89f-11e6-8ad3-7dc38ce86fb5.png)
![image](https://cloud.githubusercontent.com/assets/10401817/23179145/7ac17906-f89f-11e6-8d3a-cc23e3266b7c.png)

why?

P.S. Restart of bot fixes issue for some time:
![image](https://cloud.githubusercontent.com/assets/10401817/23179248/caf371e0-f89f-11e6-9866-9b5be082c244.png)

**Comment by drdrjojo** [comment]
IGuild.members is just a cache of online members at [GATEWAY_READY](https://qeled.github.io/discordie/#/docs/Events).
Check [IUserCollection.fetchMembers([guilds])](https://qeled.github.io/discordie/#/docs/IUserCollection?p=IUserCollection%23fetchMembers) to make sure the cache is populated with all online and offline members.
