### ISSUE TITLE
How to use guild.getBans()?

### ISSUE THREAD

**Issue by rmickey42** [qeled/discordie#87]
I'm trying to make a command in my bot to unban people. I tried to do it using mentions, but since the person was no longer on the server, I couldn't. I saw the getBans() function and thought it might be useful, but I have no idea how to use it. Could someone help me?

**Comment by drdrjojo** [comment]
You can unban Users everytime via ID as string.

getBans returns an Array of IUsers, here is an example to unban all:
```
guild.getBans().then((users) => {
   users.map((user) => { guild.unban(user); });
}).catch((error) => {
   console.error("Unable to get bans:", error);
});
```
