### ISSUE TITLE
How to set the role of an IGuildMember?

### ISSUE THREAD

**Issue by rmickey42** [qeled/discordie#88]
I am creating commands to set the role of a specified user to Default, Moderator, or Administrator. I have everything else working fine and set up correctly, but I cannot figure out how to set the role of the guild member. How would I do this?

**Comment by TTtie** [comment]
Use [IGuildMember.assignRole](https://qeled.github.io/discordie/#/docs/IGuildMember?p=IGuildMember%23assignRole&_k=bttjlz)

**Comment by rmickey42** [comment]
@TTtie I know, but I don't know how to use it. I put member.assignRole("Default"); when I wanted to change it to default, and "Moderator" for mod and "Admin" for admin, but it doesn't work.

**Comment by TTtie** [comment]
It wants either IRole or role id (IRole.id). You can simply go do
 ```js
let role = e.message.guild.roles.find(fn => fn.name == "Role name, case sensitive")
if (role) /*IGuildMember*/.assignRole(role)
```
