### ISSUE TITLE
2nd WebmOpusPlayer initializes with incorrect EncoderWorker frameDuration

### ISSUE THREAD

**Issue by mbilker** [qeled/discordie#9]
I noticed this bug after dealing with YouTube's 302 responses with requests to their WebM Opus files instead of handing the Vorbis audio to the FFmpeg player. The 2nd encoder created with `voiceConnection.createExternalEncoder(...)` causes the `frameDuration` of the underlying `EncoderWorker` to be set to its default value of `60` instead of `20`.

I am using my personal Discordie bot available [here](https://github.com/mbilker/cardinal-discord) and playing https://www.youtube.com/watch?v=RATEc0euwiU.

Some output from the internal structures on the 1st song play:
```js
-> client.VoiceConnections[0].voiceSocket.audioEncoder.options
{ multiThreadedVoice: false,
  frameDuration: 20,
  sampleRate: 48000,
  channels: 1,
  float: false,
  downmix: undefined,
  timingPrecision: 'normal',
  resampler: 'internal',
  engine: 'internal',
  proxy: true,
  bitrate: null }
```

The `EncoderWorker`'s options differs from the 1st song play and the 2nd song play.
```js
-> client.VoiceConnections[0].voiceSocket.audioEncoder.worker.options
{ multiThreadedVoice: false,
  frameDuration: 20,
  sampleRate: 48000,
  channels: 1,
  float: false,
  downmix: undefined,
  timingPrecision: 'normal',
  resampler: 'internal',
  engine: 'internal',
  proxy: true,
  bitrate: null }
```

During 2nd song play:
```js
-> client.VoiceConnections[0].voiceSocket.audioEncoder.worker.options
{ proxy: true,
  frameDuration: 60,
  sampleRate: 48000,
  channels: 1,
  float: false,
  downmix: undefined,
  timingPrecision: 'normal',
  resampler: 'internal',
  engine: 'internal',
  bitrate: null }
```

This happens with other Opus direct play to Discord. This does not happen if the FFmpeg external encoder is used.

**Comment by qeled** [comment]
Thanks. Fix released as version 0.6.3.
