### ISSUE TITLE
Bot goes offline

### ISSUE THREAD

**Issue by someguythatmods** [qeled/discordie#92]
I am using pm2 to run my discord bot and it will be running fine then I look the next day or later that day and the discord bot is offline and wont recognize any commands. I tried looking through the events so that I could just do a on disconnect - reconnect but i cant find any even to monitor disconnect

**Comment by Edsardio** [comment]
http://qeled.github.io/discordie/#/docs/Discordie?_k=n58urp

Look at the autoReconnect ;)

**Comment by someguythatmods** [comment]
Aha rip I'm stupid lol thank you for the quick response
