### ISSUE TITLE
AvatarURL webp

### ISSUE THREAD

**Issue by PhunStyle** [qeled/discordie#93]
Hey there,

![image](https://cloud.githubusercontent.com/assets/6770468/25071187/14c69492-22b1-11e7-9b77-8dbba311fbcf.png)

Was wondering if "fmt" could be changed from **jpg** to **webp** to support transparency. Apparently discord stores them in webp now.

https://cdn.discordapp.com/avatars/119807353439649796/8bfbdb5291c55a1ea802302aa4038e6c.jpg

https://cdn.discordapp.com/avatars/119807353439649796/8bfbdb5291c55a1ea802302aa4038e6c.webp

-Phun

**Comment by bluethefoxyt** [comment]
it does @PhunStyle

**Comment by bluethefoxyt** [comment]
you dont need to ask them to edit it because it automaticly does it @PhunStyle

**Comment by PhunStyle** [comment]
![image](https://cloud.githubusercontent.com/assets/6770468/25071187/14c69492-22b1-11e7-9b77-8dbba311fbcf.png)

Are you sure @kessanro ? The code explicitly only differentiates between jpg and gif, not webp/png.

**Comment by bluethefoxyt** [comment]
i use similler code and it works for me @PhunStyle

**Comment by bluethefoxyt** [comment]
but if you want to allow gift(i dont) you might need to check the documentation https://qeled.github.io/discordie/#/docs/IUser?p=IUser%23registeredAt&_k=furdu7

**Comment by PhunStyle** [comment]
IUser.avatarURL always returns jpg/gif for me, not transparent webp, even though i have a transparent avatar.

**Comment by bluethefoxyt** [comment]
ok discordie does not support transparent images you would either need to make your own lib or use a diffrent one tht might chanche in the future thow @PhunStyle here is a link to my server 
https://discord.gg/NdsBY6f

**Comment by PhunStyle** [comment]
Yeah the whole point of this issue was to ask the author of the lib to implement a change to .avatarURL so it does support transparent images...

**Comment by LynnAU** [comment]
This can probably be closed now as the dev branch has the above commit.

**Comment by PhunStyle** [comment]
Awesome, thanks qeled ♥
